name: Update Dependencies

on:
  push:
    paths:
      - 'package.json'

jobs:
  update-lockfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - run: npm install
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update lockfile
          file_pattern: package-lock.json
